# -*- coding: utf-8 -*-

# django-mcadmin
# mcadmin/migrations/0001_initial.py

# Generated by Django 2.2.7 on 2019-12-01 12:21


from typing import List, Tuple  # pylint: disable=W0611

from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: List[Tuple[str, str]]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "management commands group",
                "verbose_name_plural": "management commands groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[],
                        db_index=True,
                        help_text="got from management commands admin registry",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="mcadmin.Group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "management command",
                "verbose_name_plural": "management commands",
                "ordering": ["command"],
                "unique_together": {("command", "group")},
            },
        ),
    ]  # type: List[migrations.CreateModel]
