# -*- coding: utf-8 -*-

# django-mcadmin
# mcadmin/migrations/__init__.py


# Generated by Django 2.1.13 on 2019-11-03 04:06


from typing import List, Tuple, Union  # pylint: disable=W0611

from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True  # type: bool

    dependencies = [
        ("auth", "0009_alter_user_last_name_max_length"),
    ]  # type: List[Tuple[str, str]]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        db_index=True,
                        help_text="this list get from settings",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "management command",
                "verbose_name_plural": "management commands",
                "ordering": ["command"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "management commands group",
                "verbose_name_plural": "management commands groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="mcadmin.Group",
                        verbose_name="group",
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Group",
                        verbose_name="user group",
                    ),
                ),
            ],
            options={
                "verbose_name": "management command group permission",
                "verbose_name_plural": "management command group permissions",
                "ordering": ["group"],
            },
        ),
        migrations.AddField(
            model_name="command",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="mcadmin.Group",
                verbose_name="group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppermission", unique_together={("group", "user_group")},
        ),
        migrations.AlterUniqueTogether(
            name="command", unique_together={("command", "group")},
        ),
    ]  # type: List[Union[migrations.CreateModel, migrations.AddField, migrations.AlterUniqueTogether]]  # noqa: E501
