# -*- coding: utf-8 -*-

# django-mcadmin
# mcadmin/migrations/0002_auto_20191118_1540.py


# Generated by Django 3.0b1 on 2019-11-18 15:40


from typing import List, Tuple, Union  # pylint: disable=W0611

from django.conf import settings
from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mcadmin", "0001_initial"),
    ]  # type: List[Tuple[str, str]]

    operations = [
        migrations.AddField(
            model_name="grouppermission",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="command",
            name="command",
            field=models.CharField(
                choices=[],
                db_index=True,
                help_text="this list get from settings",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppermission", unique_together={("group", "user")},
        ),
        migrations.RemoveField(model_name="grouppermission", name="user_group",),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[],
                        db_index=True,
                        help_text="this list get from settings",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "management command permission",
                "verbose_name_plural": "management command permissions",
                "ordering": ["user"],
                "unique_together": {("command", "user")},
            },
        ),
    ]  # type: List[Union[migrations.CreateModel, migrations.AddField, migrations.AlterUniqueTogether, migrations.RemoveField, migrations.AlterField]]  # noqa: E501
