# -*- coding: utf-8 -*-

# django-mcadmin
# mcadmin/migrations/0003_auto_20191123_1732.py


# Generated by Django 3.0rc1 on 2019-11-23 17:32


from typing import List, Tuple, Union  # pylint: disable=W0611

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mcadmin", "0002_auto_20191118_1540"),
    ]  # type: List[Tuple[str, str]]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="commands", to="mcadmin.Group", verbose_name="group"),
        ),
    ]  # type: List[Union[migrations.AlterField]]
