# -*- coding: utf-8 -*-

# django-mcadmin
# mcadmin/migrations/0004_auto_20191127_1403.py


# Generated by Django 3.0rc1 on 2019-11-27 14:03


from typing import List, Tuple, Union  # pylint: disable=W0611

from django.conf import settings
from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mcadmin", "0003_auto_20191123_1732"),
    ]  # type: List[Tuple[str, str]]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="command",
            field=models.CharField(
                choices=[],
                db_index=True,
                help_text="got from management commands admin registry",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="grouppermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcadmin_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="command",
            field=models.CharField(
                choices=[],
                db_index=True,
                help_text="got from management commands admin registry",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcadmin_commands",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]  # type: List[Union[migrations.AlterField]]
